# Algorithm Parameters
# popSize: [50,150,300,500]
# eliteSize: [20,50,100,150]
# breeding_rate: [0.1,0.2,0.3,0.5]
# mutationRate: [0.001,0.01,0.05,0.1]
# generations: [100,300,500,1000]
# archiveSize: [20,50,100,150]

popSize: [150]
eliteSize: [40]
breeding_rate: [0.2]
mutationRate: [0.01]
generations: [62]
archiveSize: [40]



# Number of random combinations from algorithm parameters chosen
randomSearchIterations: 1

# Objective that is optimised: 
# 1 : Distance minimization
# 2 : Stress minimization
# 3 : Distance and Stress minimization
objectiveNrUsed: 3

# Type of Initial Population
# 1 : None
# 2 : Smallest Distances
# 3 : Best Solutions from single objective solutions for stress and distance
initialPopNrUsed: 3

# Selection type used
# 1 : Fitnessproportional
# 2 : tournament based
selectionNrUsed: 2

archiveUsed: True

# Amount of information plotted
# 0 : plot nothing
# 1 : plot final solution
# 2 : plot initial solution, stress and distance progress and final solution
# 3 : verbose plotting, plot every step of the solution for detailed debugging
plotLevel: 2